import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import WebsiteHeader from "@/components/marketing/Header";
import WebsiteFooter from "@/components/marketing/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"], // Or any desired weights
  variable: "--font-poppins", // Optional: Create a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <WebsiteHeader />
        {children}
        <WebsiteFooter />
      </body>
    </html>
  );
}
